---
title: "Reproducible documents"
author: "Simon Chang"
format: html
editor: visual
---

```{r setup}
#| message: false
#| warning: false


library(tidyverse)
post_meal_data <- read_csv2(here::here("data/post-meal-insulin.csv"))
small_post_meal_data <- select(post_meal_data, id, Age, BMI, Group, auc_pg, auc_ins, glykemi)
```


## Showing the data

```{r}
post_meal_data
glimpse(post_meal_data)
```

```{r ggplot}
library(ggplot2)
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```
## Basic histogram

```{r}
#| fig-cap: "Dist. of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```
This is my figure (@fig-bmi-histo)

## Excersice: discrete plots
```{r discrete plots}
#| fig-cap: "Grouping"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()
```

See @fig-group-bar above for a cool plot!

## Plotting two discrete

```{r two discrete}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```

## Side by side plots

```{r histogram}
post_meal_data |>
  ggplot(aes(x = BMI)) +
  geom_histogram()
```
```{r}
post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```
```{r side-by-side-plots}
#| label: fig-bmi-glycemia
#| fig-cap: "BMI and glycemia, side by side."
#| fig-subcap:
#|   - "Distribution of BMI."
#|   - "Number of those with glycemia."
#|   - "Grouping in relation to glycemia"
#| layout-ncol: 3
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()

ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()

post_meal_data |>
  ggplot(aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```
## Plotting two continuous variables

```{r two continouus}
#| fig-cap: "Scatterplot of BKI against PG"
#| label: fig-bmi-aucpg

ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point(aes(fill = Group)) +
  geom_smooth()
```
## Pushing changes to remote

Oh oh - how exciting!

## Pulling file from Github

Even more exiting

## Selecting Data

```{r}
select(post_meal_data, Age)
select(post_meal_data, Age, BMI, Weight)
select(post_meal_data, -Group)
select(post_meal_data, starts_with("Insulin"))
select(post_meal_data, ends_with("5"))
select(post_meal_data, contains("0"))
```
